version: '3.8'

services:
  # Backend service (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: devsecops-backend
    image: devsecops-tools-backend:1.0.0
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=info
    volumes:
      # Для разработки: монтируем код для hot-reload
      # Закомментируйте для production
      - ./backend/app:/app/app
    networks:
      - devsecops-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontend service (React + Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: devsecops-frontend
    image: devsecops-tools-frontend:1.0.0
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - devsecops-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  devsecops-network:
    driver: bridge
    name: devsecops-network

# Volumes для персистентности данных (если потребуется в будущем)
volumes:
  backend-data:
    name: devsecops-backend-data
